-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 09:03:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auto_forms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auto_forms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auto_forms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `auto_forms` ;

-- -----------------------------------------------------
-- Table `auto_forms`.`upload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_forms`.`upload` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `gallery_id` INT NULL COMMENT '',
  `folder` VARCHAR(255) NULL COMMENT '',
  `file` VARCHAR(255) NULL COMMENT '',
  `order` INT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_forms`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_forms`.`administrator` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `state` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  `is_super_administrator` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `permissions` TEXT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_forms`.`administrable_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_forms`.`administrable_table` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `alias` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_forms`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_forms`.`configuration` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `google_analytics_code` VARCHAR(30) NULL COMMENT '',
  `website_description` TEXT NULL COMMENT '',
  `website_keywords` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_forms`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_forms`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `administrator_id` INT NULL COMMENT '',
  `state` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  `is_private` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
